name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:

    runs-on: ubuntu-latest
    env:
      working-directory: IliasBuddy

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Test (Gradle)
      run: make test
      #working-directory: ${{env.working-directory}}

  build:

    runs-on: ubuntu-latest
    env:
      working-directory: IliasBuddy

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build debug APK (Gradle)
      run: make build_debug
      #working-directory: ${{env.working-directory}}
    - name: Upload Debug APK
      uses: actions/upload-artifact@v1
      with:
          name: app-debug
          path: ${{env.working-directory}}/app/build/outputs/apk/debug/app-debug.apk
